typography_spectrum: 0.115132
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.06549298926256597
  lightness: 0.8515575609635562
  saturation: 0.41477637318894267
  rhythmicContrast: 0.43648708797991276
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.51669
analytics:
  google: null
  facebook: null
  twitter: null
name: mauitrip
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
